/*
 * Copyright (c) 2019 Nordic Semiconductor
 *
 * SPDX-License-Identifier: LicenseRef-BSD-5-Clause-Nordic
 */

#ifndef _version_h_
#define _version_h_

/* This will be automatically generated by Makefile from version tag or
 * 0.0.0 if current commit does not have version tag assigned. */
#ifndef APP_MAJOR_VERSION 
#define APP_MAJOR_VERSION 0
#define APP_MINOR_VERSION 0
#define APP_MICRO_VERSION 0
#endif

#endif
